// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-cLmZXFiRU1Sx4cry9P5m6PLCtamAwJ0',
    appId: '1:852355898935:web:01e966c64f03ad1d5ea9b2',
    messagingSenderId: '852355898935',
    projectId: 'investify-1eba0',
    authDomain: 'investify-1eba0.firebaseapp.com',
    storageBucket: 'investify-1eba0.firebasestorage.app',
    measurementId: 'G-18JTR7988B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn8VSw3cgme-T-7YLDweNqzb42AOurHFA',
    appId: '1:852355898935:android:c49eeaafeef2f3945ea9b2',
    messagingSenderId: '852355898935',
    projectId: 'investify-1eba0',
    storageBucket: 'investify-1eba0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFMEkOIJ0RVCaUyP7uqy3l9diy-FT-Koc',
    appId: '1:852355898935:ios:82fb43378fac25e85ea9b2',
    messagingSenderId: '852355898935',
    projectId: 'investify-1eba0',
    storageBucket: 'investify-1eba0.firebasestorage.app',
    iosClientId: '852355898935-dgd03jnga1m1i2ncikhnmp43v0lbdjok.apps.googleusercontent.com',
    iosBundleId: 'com.example.investify',
  );
}
