// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlaLuwToH8QzmTTHvjnHfla4DsJ4t-YqI',
    appId: '1:910713065227:web:10ab21652235e928149c0e',
    messagingSenderId: '910713065227',
    projectId: 'invest-fc44a',
    authDomain: 'invest-fc44a.firebaseapp.com',
    storageBucket: 'invest-fc44a.firebasestorage.app',
    measurementId: 'G-HSL34EWHBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkleYbYU0YRErjRr4p9BDFUg0ly-e5qYY',
    appId: '1:910713065227:android:b60a1db4d95a4bf5149c0e',
    messagingSenderId: '910713065227',
    projectId: 'invest-fc44a',
    storageBucket: 'invest-fc44a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy-N3pb3Rk0mu5MdP7tVXe3ufuXtkfQNc',
    appId: '1:910713065227:ios:f45a88a56a1684a5149c0e',
    messagingSenderId: '910713065227',
    projectId: 'invest-fc44a',
    storageBucket: 'invest-fc44a.firebasestorage.app',
    iosBundleId: 'com.example.investify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy-N3pb3Rk0mu5MdP7tVXe3ufuXtkfQNc',
    appId: '1:910713065227:ios:f45a88a56a1684a5149c0e',
    messagingSenderId: '910713065227',
    projectId: 'invest-fc44a',
    storageBucket: 'invest-fc44a.firebasestorage.app',
    iosBundleId: 'com.example.investify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlaLuwToH8QzmTTHvjnHfla4DsJ4t-YqI',
    appId: '1:910713065227:web:ec89636ebb309c72149c0e',
    messagingSenderId: '910713065227',
    projectId: 'invest-fc44a',
    authDomain: 'invest-fc44a.firebaseapp.com',
    storageBucket: 'invest-fc44a.firebasestorage.app',
    measurementId: 'G-ZX53M2X8N2',
  );
}
